apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-status-deployment
  labels:
    app: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-pods
  template:
    metadata:
      labels:
        app: status-pods
    spec:
      containers:
        - name: status-container
          image: kube-status:latest
          imagePullPolicy: Never   # this is done so that image is fetched locally
          env: 
          - name: SPRING_PROFILES_ACTIVE
            value : "prod"
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
                configMapKeyRef:
                    key: EUREKA_URL
                    name: kube-status-configmap
            
            
        