apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-status-deployment
  labels:
    app: kube-status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-status
  template:
    metadata:
      labels:
        app: kube-status
    spec:
      volumes:
        - name: kube-status-volume
          configMap:
            name: kube-status
      containers:
        - name: kube-status-container
          image: kube-status:latest
          imagePullPolicy: Never   # this is done so that image is fetched locally
          args: ["--spring.config.additional-location=/devops-learning/config/"]
          volumeMounts:
            - name: kube-status-volume
              mountPath: /devops-learning/config
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
        