apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-pod
  template:
    metadata:
      name: http-pods
      labels:
        app: httpd-pod
    spec:
      containers:
        - name: http-container
          image: httpd:2.4-alpine