apiVersion: v1
kind: Service
metadata:
  name: kube-status-service
  namespace: default
spec:
  ports:
  - nodePort: 30080
    port: 9090
    targetPort: 9090
  selector:
    app: status-pods
  type: NodePort