apiVersion: v1
# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: postgres-configmap
  labels:
    app: postgresdb
data:
  POSTGRES_DB: learning
  POSTGRES_USER: postgres
