apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport-service
  namespace: default
spec:
  ports:
  - nodePort: 30081
    port: 5432
    targetPort: 5432
  selector:
    app: postgresdb
  type: NodePort