# Kubernetes API version
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresdb-stateful
spec:
  serviceName: postgres-headless-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb-stateful
  template:
    metadata:
      labels:
        app: postgresdb-stateful
    spec:
      containers:
        - name: postgresdb-stateful
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                    key: password
                    name: postgres-secret-config
          envFrom:
            - configMapRef:
                name: postgres-configmap
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-persistent-volume-claim