pipeline {
    agent any

    stages {
        stage("clean up") {
            steps {
				echo 'Clean Up'
                deleteDir()
            }
        }
        stage("clone") {
            steps {
                echo 'CLONE STEP'
                sh "git clone https://github.com/munish-usit/devops-learning.git"
            }
        }
        
        stage("build") {
            steps {
                echo 'BUILD STEP'
                dir("devops-learning/jenkins-tutorial") {
                    sh "mvn clean install"
                }
            }
        }
        
        stage("test") {
            steps {
                echo 'TEST STEP'
                dir("devops-learning/jenkins-tutorial") {
                    sh "mvn test"
                }
            }
        }
		
		stage ('Sonar Qube Scanner') {
            steps {
                 echo 'SONAR SCANNER'
                 dir("devops-learning/jenkins-tutorial") {
                   withSonarQubeEnv(installationName: 'sonar-qube', credentialsId: 'generic-token') {
                        sh 'mvn clean package sonar:sonar'
                    }
                 }
            }
        }
        
        stage("Quality Gate") {
            steps {
              echo 'QUALITY GATE'
              timeout(time: 1, unit: 'HOURS') {
                waitForQualityGate abortPipeline: true
              }
            }
        }
    }
}
